apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: dc1df76e68851caf2d3941e5aaa136a5c4660146
    app.quarkus.io/build-timestamp: 2024-09-12 - 00:35:43 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: eda-qs-order-producer
    app.kubernetes.io/version: 1.0.0
  name: eda-qs-order-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eda-qs-order-producer
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: dc1df76e68851caf2d3941e5aaa136a5c4660146
        app.quarkus.io/build-timestamp: 2024-09-12 - 00:35:43 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: eda-qs-order-producer
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          envFrom:
          - configMapRef:
              name: order-consumer-cm
          image: jbcodeforce/eda-qs-order-consumer:1.0.0
          imagePullPolicy: Never
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: eda-qs-order-producer
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10