apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: dc1df76e68851caf2d3941e5aaa136a5c4660146
    app.quarkus.io/build-timestamp: 2024-09-12 - 00:35:43 +0000
  labels:
    app.kubernetes.io/name: eda-qs-order-consumer
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: quarkus
  name: eda-qs-order-consumer
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: eda-qs-order-consumer
    app.kubernetes.io/version: 1.0.0
  type: NodePort 